### ISSUE TITLE
Missing partitions for photon-xavier-nx

### ISSUE THREAD

**Issue by pgils** [balena-os/balena-jetson#111]
**EDIT: This seems to be OE4T/meta-tegra#400.**

Trying to flash a v2.58.3+rev3 build for `photon-xavier-nx` with balena-os/jetson-flash#30 results in following error:
```
❯ ./bin/cmd.js -m jetson-xavier-nx-devkit-emmc -f ~/balena-jetson-hwky/build/tmp/deploy/images/photon-xavier-nx/resin-image-photon-xavier-nx.resinos-img -po ./work
Consistency check done for /home/pelle/playground/jetson-flash/work/jetson-flash-artifacts/Linux_for_Tegra
Saved in /home/pelle/playground/jetson-flash/work/jetson-flash-artifacts
Successfully generated hash
Checking resin cache
Cache image check done
Extracting partition kernel from /home/pelle/playground/jetson-flash/work/jetson-flash-artifacts/resin/img to /home/pelle/playground/jetson-flash/work/jetson-flash-artifacts/resin
(node:66729) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at Object.exports.extractPartition (/home/pelle/playground/jetson-flash/lib/utils.js:137:38)
    at async ResinJetsonFlash.generateArtifacts (/home/pelle/playground/jetson-flash/lib/resin-jetson-flash.js:249:14)
    at async ResinJetsonFlash.run (/home/pelle/playground/jetson-flash/lib/resin-jetson-flash.js:269:3)
    at async run (/home/pelle/playground/jetson-flash/bin/cmd.js:56:2)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Seems to fail trying to extract the 'kernel' partition from the image.

Printing the read partitions seems to confirm:
```
diff --git a/lib/utils.js b/lib/utils.js
index 16f2b01..3cbecd7 100644
--- a/lib/utils.js
+++ b/lib/utils.js
@@ -226,6 +226,7 @@ exports.getPartitionTableWithNames = async image => {
        const partTable = await partitionInfo.getPartitions(image);

        partTable.partitions.forEach((partition, i) => {
+               console.log(rawTable.partitions[i].name);
                partition.name = rawTable.partitions[i].name;
        });
```
```
...
Extracting partition kernel from /home/pelle/playground/jetson-flash/work/jetson-flash-artifacts/resin/img to /home/pelle/playground/jetson-flash/work/jetson-flash-artifacts/resin
resin-boot
resin-rootA
resin-rootB
resin-state
resin-data
(node:73142) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
...
```

Compared to a `jetson-xavier-nx-devkit-emmc` image:
```
...
Extracting partition kernel from /home/pelle/playground/jetson-flash/work/jetson-flash-artifacts/resin/img to /home/pelle/playground/jetson-flash/work/jetson-flash-artifacts/resin
kernel
kernel_b
kernel-dtb
kernel-dtb_b
recovery-dtb
kernel-bootctrl
kernel-bootctrl_b
PADDING
resin-boot
resin-rootA
resin-rootB
resin-state
resin-data
...
```

There is a size difference between images:
**v2.58.3+rev3**
```
❯ du -h build/tmp/deploy/images/{jetson-xavier-nx-devkit-emmc,photon-xavier-nx}/resin-image*rootfs.resinos-img
1.8G    build/tmp/deploy/images/jetson-xavier-nx-devkit-emmc/resin-image-jetson-xavier-nx-devkit-emmc-20201008124920.rootfs.resinos-img
1.2G    build/tmp/deploy/images/photon-xavier-nx/resin-image-photon-xavier-nx-20201008121608.rootfs.resinos-img
```

**v2.56.0+rev4**
```
❯ du -h build/tmp/deploy/images/{jetson-xavier-nx-devkit-emmc,photon-xavier-nx}/resin-image*rootfs.resinos-img
1.8G    build/tmp/deploy/images/jetson-xavier-nx-devkit-emmc/resin-image-jetson-xavier-nx-devkit-emmc-20201008134238.rootfs.resinos-img
1.8G    build/tmp/deploy/images/photon-xavier-nx/resin-image-photon-xavier-nx-20201008135335.rootfs.resinos-img
```

`jetson-xavier-nx-devkit-emmc` and `photon-nano` work fine.

Do you have an idea what could be the issue here @acostach ?

**Comment by acostach** [comment]
Hi @pgils , I'll have a look at what may cause this and get back to you

**Comment by pgils** [comment]
thanks @acostach. I think this is OE4T/meta-tegra#400.
Due to most of `jetson-xavier-nx-devkit-emmc.conf` being split off into `xavier-nx.conf`, `jetson-xavier-nx-devkit-emmc` is somehow absent from `MACHINEOVERRIDES`:
```
$ bitbake -e resin-image |grep MACHINEOVERRIDES
...
MACHINEOVERRIDES="cuda:tegra:aarch64:armv8a:tegra194:xavier-nx:photon-xavier-nx"
...
```

hard-coding the `MACHINEOVERRIDES` to include both `xavier-nx` and `jetson-xavier-nx-devkit-emmc` as described in that thread fixes it:
```
MACHINEOVERRIDES = "cuda:tegra:tegra194:xavier-nx:jetson-xavier-nx-devkit-emmc:${MACHINE}"
```

I'm currently trying to find a slightly more elegant way to get `jetson-xavier-nx-devkit-emmc` back in this array.

**Comment by acostach** [comment]
@pgils indeed, that seems to be it, feel free to PR the one that works best for you
